version: "2"


services:
  go:
    image: jorge-go-slides
    build:
      context: .
      dockerfile: Dockerfile-go
    env_file: .env
    command: /go/bin/present
    ports:
      - $GOPORT:3999
    volumes:
      - ./2017:/slides/2017
      - ./2018:/slides/2018
      - ./$PRESENT:/slides/present
      - ./$COMMONDIR:/slides/common

  js:
    image: jorge-js-slides
    build:
      context: .
      dockerfile: Dockerfile-js
    env_file: .env
    command: npm start
    ports:
      - $JSPORT:8000
    volumes:
      - ./2017:/slides/2017
      - ./2018:/slides/2018
      - ./$REVEALCSS:/slides/css
      - ./$COMMONDIR:/slides/common
